predictors:
    cortexA76cpu_tflite21:
      version: 1.0 
      kernel_predictors: 
        - conv-bn-relu
        - dwconv-bn-relu
        - fc
        - global-avgpool
        - hswish
        - relu
        - se
        - split
        - add
        - addrelu
        - maxpool
        - avgpool
        - bn
        - bnrelu
        - channelshuffle
        - concat
      download: https://github.com/Lynazhang/nnmeter/releases/download/version1.0/cortexA76cpu_tflite21.zip
  
    adreno640gpu_tflite21:
      version: 1.0 
      kernel_predictors: 
        - conv-bn-relu
        - dwconv-bn-relu
        - hswish
        - relu
        - se
        - maxpool
        - avgpool
        - bn
        - bnrelu
        - concat
      download: https://github.com/Lynazhang/nnmeter/releases/download/version1.0/adreno640gpu_tflite21.zip
    
    adreno630gpu_tflite21:
      version: 1.0 
      kernel_predictors: 
        - conv-bn-relu
        - dwconv-bn-relu
        - hswish
        - relu
        - se
        - maxpool
        - avgpool
        - bn
        - bnrelu
        - concat
      download: https://github.com/Lynazhang/nnmeter/releases/download/version1.0/adreno630gpu_tflite21.zip
    
    myriadvpu_openvino2019r2:
      version: 1.0 
      kernel_predictors: 
        - conv-bn-relu
        - dwconv-bn-relu
        - fc
        - hswish
        - relu
        - se
        - addrelu
        - maxpool
        - avgpool
        - bn
        - bnrelu
        - channelshuffle
      download: https://github.com/Lynazhang/nnmeter/releases/download/version1.0/myriadvpu_openvino2019r2.zip