name: Integrated Test

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.10

    - name: Cache
      uses: actions/cache@v2
      env: 
        cache-name: download-cache
      with:
        path: |
          /home/runner/work/nn-Meter/data/testmodels
          /home/runner/work/nn-Meter/nn-Meter/~/.nn_meter
        key: ${{hashFiles('setup.py')}}-${{hashFiles('nn_meter/configs/predictors.yaml')}}

    - name: Install dependencies
      run: |
        pip install tensorflow==1.15.0
        pip install onnx==1.9.0
        pip install torch==1.9.0
        
    - name: Install nn-Meter
      run: pip install .

    - name: Integration test
      run: python tests/integration_test.py
    
    - name: Diff result with reference
      run: diff tests/test_result.txt tests/reference_result.txt
