# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: Integrated Test for Torch Model Based on ONNX

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.10

    - name: Cache
      uses: actions/cache@v2
      id: cache
      env: 
        cache-name: download-cache
      with:
        path: |
          ~/.nn_meter
          /home/runner/work/nn-Meter/data/testmodels
          /opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages
        key: Data-${{hashFiles('nn_meter/configs/predictors.yaml')}}-Test-${{hashFiles('tests/integration_test.py')}}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        pip install tensorflow==1.15.0
        pip install onnx==1.9.0
        pip install torch==1.9.0
        pip install torchvision==0.10.0
        pip install onnx-simplifier
        
    - name: Install nn-Meter
      run: pip install -U .

    - name: Integration test
      run: nn-meter lat_pred --torchvision resnet18 alexnet vgg16 squeezenet densenet161 inception_v3 googlenet shufflenet_v2 mobilenet_v2 resnext50_32x4d wide_resnet50_2 mnasnet --predictor myriadvpu_openvino2019r2 --predictor-version 1.0
    
    - name: Diff result with reference
      run: diff tests/reference_result_onnx_based_torch.txt tests/test_result_onnx_based_torch.txt
        
