name: Integrated Test

on: [push]

jobs:
  integrated-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.10
    - name: Install dependencies
      run: |
        # install dependencies for testing
        pip install -r tests/requirements.txt 
        pip list
    - name: Install nn-Meter
      run: |
        # install nn-meter
        python setup.py install # try1
        python setup.py sdist bdist_wheel # try2
        pip install dist\nn_meter-1.0-py3-none-any.whl # try2
        pip list
    - name: Integration test
      run: |
        python tests/integration_test.py
        diff tests/test_result.txt tests/reference_result.txt
