name: Integrated Test

on: [push]

jobs:
  integrated-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.10
    - name: Install nn-Meter and dependencies
      run: |
        # install dependencies for testing
        pip install -r tests/requirements.txt 
        # install nn-meter
        python setup.py install
        # for debug
        pip list
    - name: Integration test
      run: |
        nn-meter -h
        python tests/integration_test.py
        diff tests/test_result.txt tests/reference_result.txt
